<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyTitle>IctBaden.RevolutionPi</AssemblyTitle>
    <Title>.NET support library for data exchange with RevPi I/O-Modules and Gateways</Title>
    <Description>.NET support library for data exchange with RevPi I/O-Modules and Gateways (btc.jost fork)</Description>
    <Version>1.0.0</Version>
    <Authors>btc.jost AG</Authors>
    <Company>btc.jost AG</Company>
    <Product>RevolutionPi .NET Library</Product>
    <Copyright>Copyright © 2017-2021 ICT Baden GmbH; fork © 2025 btc.jost AG</Copyright>
    <PackageProjectUrl>https://github.com/btc-jost/RevolutionPi</PackageProjectUrl>
    <RepositoryUrl>https://github.com/btc-jost/RevolutionPi</RepositoryUrl>
    <PackageTags>RevolutionPi .NET Library</PackageTags>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>
</Project>
