<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyTitle>IctBaden.RevolutionPi</AssemblyTitle>
    <LangVersion>9</LangVersion>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>IctBaden.RevolutionPi</PackageId>
    <Authors>Frank Pfattheicher</Authors>
    <Title>.NET support libraries for data exchange with RevPi I/O-Modules and Gateways</Title>
    <Description>.NET support libraries for data exchange with RevPi I/O-Modules and Gateways</Description>
    <Copyright>Copyright ICT Baden GmbH 2017-2021</Copyright>
    <PackageProjectUrl>https://github.com/FrankPfattheicher/RevolutionPi</PackageProjectUrl>
    <PackageTags>RevolutionPi .NET Library</PackageTags>
    <PackageReleaseNotes>Net standard version</PackageReleaseNotes>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageIcon>icon64.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/FrankPfattheicher/RevolutionPi</RepositoryUrl>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\RevPi-AssemblyInfo.cs">
      <Link>Properties\RevPi-AssemblyInfo.cs</Link>
    </Compile>
    <None Include="..\icon64.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>